### ISSUE TITLE
机构类型——无法收起下级机构

### ISSUE THREAD

**Issue by heng4719** [gopark001/gotools#6]
系统管理-机构类型，给商户新增了两个下级机构，无法点击左侧横杠将其下的下级机构收起
![8-1](https://user-images.githubusercontent.com/32516279/61445472-09fd1600-a980-11e9-9073-5d413acb1fba.png)
![8-2](https://user-images.githubusercontent.com/32516279/61445474-0a95ac80-a980-11e9-92e9-8f22887ca247.png)

**Comment by wangwei123** [comment]
根据配置初始化的数据，不能删除，否则会破坏权限层级关系
